---
- name: "adding neo4j apt key"
  shell: wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -

- name: "removing previous neo4j.list"
  shell: sudo rm -rf /etc/apt/sources.list.d/neo4j.list 
         
- name: "adding neo4j repo"
  shell: echo 'deb https://debian.neo4j.com stable 4.4' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  
- name: "sudo apt update"
  shell: sudo apt update -y
  

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - ffuf
      - rlwrap 
      - exploitdb 
      - krb5-user 
      - snapd 
      - mingw-w64
      - feroxbuster 
      - snapd 
      - proxychains4 
      - samba 
      - libsasl2-modules-gssapi-mit 
      - libssl-dev 
      - npm 
      - natpmpc
      - openjdk-11-jdk
      - apt-transport-https
        #- neo4j=1:4.4.20
    state: latest
  become: true
  become_method: sudo

- name: "Install neo4j=1:4.4.20"
  shell: sudo apt install neo4j=1:4.4.20 -y

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying neo4j wrapper"
  copy:
    src: "files/neo4j"
    dest: "{{ build_dir.path }}/neo4j"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Moving to /usr/bin/"
  shell: "sudo mv {{ build_dir.path }}/neo4j /usr/bin/"
