---
- name: "adding neo4j apt repository"
  shell: wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add - echo 'deb https://debian.neo4j.com stable 4.4' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - ffuf
      - rlwrap 
      - exploitdb 
      - krb5-user 
      - snapd 
      - mingw-w64
      - feroxbuster 
      - snapd 
      - proxychains4 
      - samba 
      - libsasl2-modules-gssapi-mit 
      - libssl-dev 
      - npm 
      - natpmpc
      - openjdk-11-jdk
      - apt-transport-https
      - neo4j=1:4.4.20
    state: latest
  become: true
  become_method: sudo

- name: "Copy Neo4j wrapper script"
  copy:
    src: "{{ role_path }}/files/neo4j"
    dest: "{{ ansible_env.HOME }}"
    shell: sudo mv ~/neo4j /usr/bin && sudo chmod +x /usr/bin/neo4j 

