---
- name: "Copy Neo4j wrapper script"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - ffuf
      - rlwrap 
      - exploitdb 
      - krb5-user 
      - snapd 
      - mingw-w64
      - feroxbuster 
      - snapd 
      - proxychains4 
      - samba 
      - libsasl2-modules-gssapi-mit 
      - libssl-dev 
      - npm 
      - natpmpc
      - openjdk-11-jdk
      - apt-transport-https
      - neo4j=1:4.4.20
    state: latest
  become: true
  become_method: sudo

- name: "Copy Neo4j wrapper script"
  copy:
    src: "{{ role_path }}/files/neo4j"
    dest: "{{ ansible_env.HOME }}../../../usr/bin/"
  become: true
  become_method: sudo
