---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying script to add neo4j repository"
  copy:
    src: "files/neo4j.sh"
    dest: "{{ build_dir.path }}/neo4j.sh"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Running neo4j.sh"
  shell: "{{ build_dir.path }}/neo4j.sh"
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - ntpdate
      - flameshot
      - ffuf
      - rlwrap 
      - exploitdb 
      - krb5-user 
      - snapd 
      - mingw-w64
      - feroxbuster 
      - snapd 
      - proxychains4 
      - samba 
      - libsasl2-modules-gssapi-mit 
      - libssl-dev 
      - npm 
      - natpmpc
      - openjdk-11-jdk
      - apt-transport-https
      - neo4j=1:4.4.20
    state: latest
  become: true
  become_method: sudo

- name: "Copy Neo4j wrapper script"
  copy:
    src: "{{ role_path }}/files/neo4j"
    dest: "{{ ansible_env.HOME }}../../../usr/bin/"
  become: true
  become_method: sudo
