---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", location: "/opt/SharpCollection" }
    - { repo: "https://github.com/samratashok/nishang.git", location: "/opt/nishang" }
    - { repo: "https://github.com/danielmiessler/SecLists.git", location: "/opt/SecLists" }
    - { repo: "https://github.com/synacktiv/php_filter_chain_generator.git", location: "/opt/php" }
  become: true
  become_method: sudo

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying python script to download github releases"
  copy:
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop:
    - { repo: "jpillora/chisel",  regex: "_linux_amd64.gz", location: "/opt/chisel" }
    - { repo: "jpillora/chisel",  regex: "_windows_amd64.gz", location: "/opt/chisel" }
    - { repo: "carlospolop/PEASS-ng",  regex: "linpeas.sh", location: "/opt/peas" }
    - { repo: "carlospolop/PEASS-ng",  regex: "winPEASx64.exe", location: "/opt/peas" }
    - { repo: "WithSecureLabs/chainsaw",  regex: "chainsaw_all_", location: "/opt/" }
    - { repo: "BloodHoundAD/BloodHound", regex: "BloodHound-linux-x64.zip", location: "/opt/" }
    - { repo: "antonioCoco/RunasCs", regex: "RunasCs.zip", location: "/opt/runasCs" }
    - { repo: "DominicBreuker/pspy", regex: "pspy64", location: "/opt/pspy" }
    - { repo: "DominicBreuker/pspy", regex: "pspy32", location: "/opt/pspy" }
    - { repo: "vinsworldcom/NetCat64", regex: "nc64.exe", location: "/opt/nc64" }
    - { repo: "vinsworldcom/NetCat64", regex: "nc64-32.exe", location: "/opt/nc64" }
    #- { repo: "opsec-infosec/nmap-static-binaries", regex: "nmap-x64.tar.gz", location: "/opt/nmap-x64" }
    #- { repo: "opsec-infosec/nmap-static-binaries", regex: "nmap-x86_64.tar.gz", location: "/opt/nmap-x86_64" }
  async: 45
  poll: 0
  become: true
  become_method: sudo
