---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'AutoRecon', url: 'git+https://github.com/Tib3rius/AutoRecon.git'}
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'crackmapexec', url: 'git+https://github.com/mpgn/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'pypykatz', url: 'git+https://github.com/skelsec/pypykatz.git' }
    - { name: 'bloodhound', url: 'git+https://github.com/fox-it/BloodHound.py' }
