---
- name: "Copy BashRC"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"

- name: "mkdir MrParrot"
  shell: mkdir -p ~/.themes/MrParrot/
   
- name: "Copying MrParrot theme"
  copy:
    src: "{{ role_path }}/files/index.theme"
    dest: "{{ ansible_env.HOME }}/.themes/MrParrot/"

- name: "Read current mate terminal profiles"
  dconf:
    key: "/org/mate/terminal/global/profile-list"
    state: "read"
  register: "profile_list"

- name: "profile_list was not set, setting"
  set_fact:
    profile_list: 
      value: '["default"]'
  when: profile_list.value is none

- name: "Adding our profile"
  set_fact:
    new_profile_list: "{{ profile_list.value | regex_replace(']$', \", 'SaintShell']\") }}"

- name: "Writing updated profile list"
  dconf:
    key: "/org/mate/terminal/global/profile-list"
    value: "{{ new_profile_list }}"
  when: "'SaintShell' not in profile_list.value"
- name: "Restoring SaintShell Profile from Dump"
  shell:
    cmd: "dconf load /org/mate/terminal/profiles/SaintShell/ < {{ role_path }}/files/dconf-dump-video"
  when: "'SaintShell' not in profile_list.value"

